
/*
PAÑALES:J02010301-6A
DESODORANTE: J02020303-65A
GASESOSA:J01020103-6B
FORMLUALACTEA:J01010304-5AJ01,
CAFE:J01010702-3B,
LECHE:J01010704-3B,
*/

export const dataDura = [
    {
        "id": "41231992",
        "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/img-ew8i0Czu.jpg",
        "name": "CAFÉ SELECTO 454 GR",
        "prices": 16.9,
        "codigosku": "41231992",
        "codigojerarquia":"J01010702",
        "codigopasillo":"3B",
        "codigopais": "PE",
        "nombreproducto": "cafe",
        "codigotienda": "123",
        "mapa": " https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",
        "marca": "nescafe",
        "ean": "7754308001186",
        "description": "¿Dónde podrás encontrar el mejor café del mercado y a un buen precio? ¡Pues en Tottus! Tenemos para ti este café selecto de la marca Cafetal, el cual está fabricado con el más fino café arábico 100% peruano. El proceso de fabricación es el mismo que viene usando desde hace más de 55 años, con una selección y conservación de máxima calidad para llevar a tu mesa un producto competitivo en el mercado.\nSi quieres darle un toque único de sabor a tu leche evaporada o descremada, te recomendamos usar este riquísimo café selecto de la marca Cafetal. ¡Siente todo su sabor desde el primer sorbo!"
    },
    {
        "id": "41267292",
        "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41267292-5MUHex4J.jpg",
        "name": "CAFÉ INSTANTÁNEO GOLD BLEND 200 GR",
        "prices": 37.9,
        "codigosku": "41267292",
        "codigojerarquia":"J01010702",
        "codigopasillo":"3B",
        "codigopais": "PE",
        "nombreproducto": "cafe",
        "codigotienda": "123",
        "mapa": " https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",
        "marca": "nescafe",
        "ean": "7613035818583",
        "description": "Este café Gold Blend de la marca Nescafé es un producto soluble premium con una textura, aroma y sabor equilibrado. Está fabricado a base de café arábico molido hasta diez veces, proceso por el cual consiguen liberar todo su aroma grano por grano. Como los buenos cafés, es rico en antioxidantes que favorecen al organismo para llenarlo de energía y vitalidad. ¡Consíguelo a buen precio a través de la web de Tottus!\nComprueba su aroma de calidad mezclándolo con una leche descremada, pizcas de azúcar y gotas de miel de abeja. ¿Te sorprende esta combinación? ¡Pruébala y verás que te encantará!"
    },
    
        {
            "id": "41119510",
            "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/img-VL4OOhGb.jpg",
            "name": "LECHE EVAPORADA ENTERA",
            "prices": 3.4,
            "codigosku": "41119510",
            "codigojerarquia":"J01010704",
            "codigopasillo":"3B",
            "codigopais": "PE",
            "nombreproducto": "leche",
            "codigotienda": "123",
            "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",
            "marca": "gloria",
            "ean": "7751271021975",
            "description": "Leche Evaporada Entera"
        },
       
        {
            "id": "40273228",
            "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/img--0_ysZk3.jpg",
            "name": "LECHE UHT ENTERA X 1 LT",
            "prices": 13.5,
            "codigosku": "40273228",
            "codigojerarquia":"J01010704",
            "codigopasillo":"3B",
            "codigopais": "PE",
            "nombreproducto": "leche",
            "codigotienda": "123",
            "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010704-3B.jpg",
            "marca": "gloria",
            "ean": "7751271019972",
            "description": "LECHE ENTERA UHT"
        },
        {
            "id": "40983924",
            "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/40983924-wH91kJeE.jpg",
            "name": "LECHE UHT SIN LACTOSA 4 UNDS",
            "prices": 19.9,
            "codigosku": "40983924",
            "codigojerarquia":"J01010704",
            "codigopasillo":"3B",
            "codigopais": "PE",
            "nombreproducto": "leche",
            "codigotienda": "123",
            "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010704-3B.jpg",
            "marca": "laive",
            "ean": "7750151004589",
            "description": "Esta leche sin lactosa de la marca Laive te da la oportunidad de probar un riquísimo producto sin padecer aquellas incómodas molestias originadas por la intolerancia a la lactosa. Al ser esta una leche más ligera, tiene en su composición menos grasa y recibe mayores nutrientes como el calcio y el fósforo. Por otro lado, a diferencia de la leche común con lactosa, este producto es más ligero y facilita la buena digestión del organismo. ¡Tottus siempre piensa en ti en cada producto!\nTe recomendamos consumir esta leche sin lactosa con algún producto integral u orgánico, ya sea un snack o unas galletas. De esa manera mantendrás una dieta equilibrada durante tu alimentación."
        },
        
            {
                "id": "40482737",
                "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/img-zodi9riN.jpg",
                "name": "PAÑAL RECIEN NACIDO RN (HASTA 4 KG)",
                "prices": 7.5,
                "codigosku": "40482737",
                "marca": "babysec",
                "codigojerarquia":"J02010301",
                "codigopasillo":"6A",
                "codigopais": "PE",
                "nombreproducto": "pañal",
                "codigotienda": "123",
                "mapa":"https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02010301-6A.jpg",
                "ean": "7502247331549",
                "description": ""
            },
            {
                "id": "41893081",
                "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41893081-RQCUyTpt.jpg",
                "name": "PAÑALES PREMIUM TALLA P (HASTA A 6 KG) 62 UNIDADES",
                "prices": 27.5,
                "codigosku": "41893081",
                "codigojerarquia":"J02010301",
                "codigopasillo":"6A",
                "codigopais": "PE",
                "nombreproducto": "pañal",
                "codigotienda": "123",
                "marca": "babysec",
                "mapa":"https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02010301-6A.jpg",
                "ean": "7759185005999",
                "description": "PAÑAL PREMIUM TALLA P (HASTA A 5 KG) 62 UNIDADES"
            },
            {
                "id": "41760185",
                "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41760185-oWNeVQHA.jpg",
                "name": "PAÑAL SUPER ABSORBENTE TALLA P (HASTA 6 KG)",
                "prices": 26.9,
                "codigosku": "41760185",
                "marca": "tottus",
                "codigojerarquia":"J02010301",
                "codigopasillo":"6A",
                "codigopais": "PE",
                "nombreproducto": "pañal",
                "codigotienda": "123",
                "mapa":"https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02010301-6A.jpg",
                "ean": "2000417601850",
                "description": ""
            },
                            {
                    "id": "40985684",
                    "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/40985684-X-MRw0io.jpg",
                    "name": "Desodorante Fresh",
                    "prices": 10.5,
                    "codigosku": "40985684",
                    "codigojerarquia":"J02020303",
                    "codigopasillo":"65A",
                    "codigopais": "PE",
                    "nombreproducto": "Desodorante",
                    "codigotienda": "123",
                    "marca": "old-spice",
                    "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02020303-65A.jpg",
                    "ean": "7506309898889",
                    "description": "DESODORANTE SUDOR DEFENSE EXTRA FRESH"
                },
                {
                    "id": "41152615",
                    "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41152615-W4Xt_Dv_.jpg",
                    "name": "Desodorante Leña",
                    "prices": 10.5,
                    "codigosku": "41152615",
                    "codigojerarquia":"J02020303",
                    "codigopasillo":"65A",
                    "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02020303-65A.jpg",
                    "marca": "old-spice",
                    "codigopais": "PE",
                    "nombreproducto": "Desodorante",
                    "codigotienda": "123",
                    "ean": "7506339390254",
                    "description": "DESODORANTE LEÑA"
                },
                {
                    "id": "40921091",
                    "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/40921091-UE_CmzJK.jpg",
                    "name": "Desodorante Wolfthorn",
                    "prices": 10.5,
                    "codigosku": "40921091",
                    "codigojerarquia":"J02020303",
                    "codigopasillo":"65A",
                    "codigopais": "PE",
                    "nombreproducto": "Desodorante",
                    "codigotienda": "123",
                    "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J02020303-65A.jpg",
                    "marca": "old-spice",
                    "ean": "7506309839141",
                    "description": "DESODORANTE WOLFTHORN"
                },
                
                    {
                        "id": "41930781",
                        "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41930781-pofPnX_E.jpg",
                        "name": "FÓRMULA LÍQUIDA DE CONTINUACIÓN NAN® 2 BEBÉS 6X400G",
                        "prices": 27.6,
                        "codigosku": "41930781",
                        "codigojerarquia":"J01010702",
                        "codigopasillo":"3B",
                        "codigopais": "PE",
                        "nombreproducto": "Desodorante",
                        "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",

                        "codigotienda": "123",
                        "marca": "nan",
                        "ean": "7613037075342",
                        "description": "Llegó Nan® 2, la única fórmula láctea de seguimiento para tu bebé desde los 6 meses. Es un producto que te ayudará en el idóneo y correcto desarrollo de su sistema inmunitario.\nNan® 2 Bebés contiene 25 vitaminas y minerales, hierro, y prebióticos que alimenta a su bebé de la manera más práctica y saludable posible.\nAdemás, cuenta con un sabor muy rico y rinde para más de 3 tomas, dando tranquilidad y satisfacción tanto para ti como para su bebé. Sin duda, siempre hay que darle lo mejor a nuestras familias."
                    },
                    {
                        "id": "41930780",
                        "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41930780-98gLPBge.jpg",
                        "name": "FÓRMULA LÍQUIDA DE CONTINUACIÓN NAN® 2 BEBÉS 400G",
                        "prices": 4.6,
                        "codigosku": "41930780",
                        "codigojerarquia":"J01010702",
                        "codigopasillo":"3B",
                        "codigopais": "PE",
                        "nombreproducto": "Desodorante",
                        "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",
                        "marca": "nan",
                        "ean": "7613037074338",
                        "description": "Única fórmula líquida para bebés desde los 6 meses. NAN® 2 Bebés. Contiene 25 vitaminas y minerales, hierro, y prebióticos"
                    },
                    {
                        "id": "41930782",
                        "images": "https://e39a9f00db6c5bc097f9-75bc5dce1d64f93372e7c97ed35869cb.ssl.cf1.rackcdn.com/41930782-7-tC3QP3.jpg",
                        "name": "FÓRMULA LÍQUIDA DE CRECIMIENTO NAN® 3 CRECIMIENTO 400G",
                        "prices": 4.5,
                        "codigosku": "41930782",
                        "codigojerarquia":"J01010702",
                        "codigopasillo":"3B",
                        "codigopais": "PE",
                        "nombreproducto": "Desodorante",
                        "mapa":" https://storage.googleapis.com/tot-bi-corp-chatbot-dev.appspot.com/EXPERIENCIA-DIGITAL/PE/LABORATORIA/123/J01010702-3B.jpg",
                        "marca": "nan",
                        "ean": "7613037075403",
                        "description": "¡Única fórmula líquida recomendada por pediatras! NAN® 3 Crecimiento contiene 25 vitaminas y minerales, hierro, prebióticos y ahora el doble de DHA*. Nutrientes que apoyan un adecuado crecimiento y desarrollo de tu pequeño. Para niños desde los 2 años.                                             *En comparación con la fórmula anterior."
                    }
                
     
        
]